Проверяем рабочий процесс
htmlacademy-ecmascript/1482089-big-trip-14 pull request #1
Opened 2021-03-30 16:29 UTC by IvanLysukhin

---
:mortar_board: [Проверяем рабочий процесс](https://up.htmlacademy.ru/ecmascript/14/user/1482089/tasks/1)

:boom: https://htmlacademy-ecmascript.github.io/1482089-big-trip-14/1/

2021-03-30 16:32 UTC, IvanLysukhin commented on webpack.config.js
> +    watchContentBase: true,
Не очень понял как настроить автоматическое обновлении браузера при изменении в файлах(
Все работает сервер поднимается и webpack -- --watch запускаю, но вот автоматически браузер не обновляется, в ручную все норм

2021-03-31 11:30 UTC, ant1quar requested changes
В целом хорошо. первые два задания отлично. коммент по вебпаку описал.
Но дробление на компоненты можно сделать чуть лучше - чтобы после было меньше багов. Попробуй завести объект с данными и реализовать через цикл генерацию верстки, подсовывая нужные данные.

2021-03-31 11:30 UTC, ant1quar commented on webpack.config.js
> +    watchContentBase: true,
запускать нужно через `npm start` - запустится не `webpack`, а `webpack-dev-server --open`

2021-03-31 11:30 UTC, ant1quar commented on src/view/edit-trip-point.js
> +
А давай эти элементы в цикле выведем? а то очень много однотипного кода

2021-03-31 11:30 UTC, ant1quar commented on src/view/edit-trip-point.js
> +
Тут тоже куча одинаковой разметки, отличаются только данными. Попробуй подробить

2021-03-31 11:30 UTC, ant1quar commented on src/view/filters.js
> +                </div>
Фильтры прям тоже напрашиваются на допилинг

2021-03-31 11:30 UTC, ant1quar commented on src/view/new-trip-point.js
> +
И тут тоже

2021-03-31 11:31 UTC, merged