Поправил моки типов точек и зависимых предложений
htmlacademy-ecmascript/1482089-big-trip-14 pull request #10
Opened 2021-04-26 07:10 UTC by IvanLysukhin

2021-04-26 07:15 UTC, IvanLysukhin commented on src/constants.js
> +    },
Изменил моки
Мне кажется, что так логичнее будет
То есть у определённого типа маршрута может быть конкретный набор предложений.
К примеру у такси есть возможность поменять на бизнес-класс, а у самолета добавить обед

2021-04-26 10:11 UTC, IvanLysukhin commented
Добавил в моки состояние выбранной или не выбранной опции точки маршрута, и в зависимости от состояния точка в списке отрисовывается по разному
А в форме редактирования точки отмечаются уже выбранные опции

2021-04-27 08:39 UTC, IvanLysukhin commented on src/view/edit-trip-point.js
> +        options: DATA.POINT_TYPES[index].offers,
Здесь пока поставил зависимость от исходных данных.
У меня логика такая: у такси, к примеру, может быть определённый набор доп. предложений, поэтому в зависимости от выбора пользователя, ищу в массиве объектов нужный тип и его доп. предложений и записываю их в объект точки маршрута. 
Предполагаю, что в будущем при работе с сетью, набор доп. предложений к определённым типам будет приходить с сервера.

2021-04-27 08:40 UTC, IvanLysukhin commented on src/view/edit-trip-point.js
> +    });
Здесь поступил похожим образом, как и с типами точек, только каждый раз при изменении города - случайно генерица новый текст описания.

2021-04-27 08:41 UTC, IvanLysukhin commented on src/view/edit-trip-point.js
> +    });
Насколько это вообще сейчас допустимо? И если нет откуда мне тогда брать данные?

2021-04-27 18:28 UTC, IvanLysukhin commented
По ДЗ вроде все сделал.
Но есть пара проблемных зон.
1. Не могу додуматься как связать данные о выбранных опциях(которые приходят в моковом объекте точки options).https://skr.sh/s7mm9crhGDV?a
Чтобы при открытии формы редактирования чекбоксы уже были checked

2. Обратная ситуация: отметив нужные чекбоксы опций при сохранении данных их нужно отрисовать списком в точке маршрута в общем списке точек 
Отметили https://skr.sh/s7mvP0ZymI7?a
Отрисовали список https://skr.sh/s7mLsCHVLWO?a

2021-04-28 07:51 UTC, IvanLysukhin commented on src/view/edit-trip-point.js
> +  }
Теперь работает 
По клику на конкретный чекбокс в изначальном массиве ищем его индекc и по индексу меняется значение isChecked и пересоберая массив опций

Но 'меня терзаются смутные сомнения', что это не то решение(

2021-05-02 22:56 UTC, ant1quar requested changes

2021-05-02 22:56 UTC, ant1quar commented on src/utils/common.js
> +  return array.slice(generateRandomNumber(0, array.length), generateRandomNumber(0, array.length));
Интересно, а что будет, если start будет больше, чем end?

2021-05-02 22:56 UTC, ant1quar commented on src/utils/render-DOM-elements.js
> +};
В целом идея правильная, но я б отделил текст типа от уникального идентификатора. у тебя ж есть библиотека для генерации `id`, ее можно тут применить

2021-05-02 22:56 UTC, ant1quar commented on src/constants.js
> +    },
Идея верная, но много повторений. У нас есть конечный список предложений.
Для каждого типа транспортного средства доступны некоторые из общего списка.
Можно вынести общий список предложений в отдельную структуру и добавил им id
а в списке типов транспортных средств создал массив айдишников предложений

2021-05-02 22:56 UTC, ant1quar commented on src/view/edit-trip-point.js
> +  }
а давай через деструктуризацию сделаем. так красивее

2021-05-02 22:56 UTC, ant1quar commented on src/view/edit-trip-point.js
> +    });
Не совсем понимаю почему б не сгенерить описание сразу? у тебя уже готовые данные будут прилетать с серва.

2021-05-02 22:56 UTC, ant1quar commented on src/view/checkbox-list.js
> +      <label class="event__type-label  event__type-label--${lowerType}" for="event-type-${lowerType}-1"  data-point-type="${type.toLowerCase()}">${type}</label>
У тебя ж есть loverType.
```suggestion
      <label class="event__type-label  event__type-label--${lowerType}" for="event-type-${lowerType}-1"  data-point-type="${lowerType}">${type}</label>
```

2021-05-02 22:56 UTC, ant1quar commented on src/view/edit-trip-point.js
> +  const checkboxTypes = new CheckboxTypeListView(typesArray).getTemplate();
В промежуточной структуре `typesArray` нет смысла. Ты можешь прямо в `CheckboxTypeListView` воткнуть весь массив DATA.POINT_TYPES.
а там, внутри генерации списка чекбоксов деструктуризацией получать нужное поле. Так `array.map(({type}) => {`

2021-05-02 22:56 UTC, ant1quar commented on src/view/edit-trip-point.js
>  const createEditTripPoint = (obj) => {
```suggestion
const createEditTripPoint = ({date, city, destinations, pointType, price, defaultOptions, hasOptions, hasDestinationInfo, infoText}) => {
```

2021-05-02 22:56 UTC, ant1quar commented on src/view/edit-trip-point.js
>  const createEditTripPoint = (obj) => {
и 12я строка не нужна. можно деструктурировать сразу

2021-05-03 23:33 UTC, merged