Module2 task1
htmlacademy-ecmascript/1482089-big-trip-14 pull request #4
Opened 2021-04-04 12:32 UTC by IvanLysukhin

2021-04-04 12:33 UTC, IvanLysukhin commented on src/mock/mocks.js
> +    //duration:,
Здесь проблемка( 
Не могу додуматься как найти продолжительность события? Поиска в документации dayjs, не нашёл или плохо искал

2021-04-04 12:38 UTC, IvanLysukhin commented on src/utils.js
> +};
Здесь нахожу первое и последнее число путешествия, с помощью плагина dayjs (https://day.js.org/docs/en/get-set/max). Только линтер ругается.
Или нужно это как-то иначе искать?

2021-04-04 12:39 UTC, IvanLysukhin commented on src/utils.js
> +const minMax = require('dayjs/plugin/minMax');
вот здесь линтер ругается. Я как-то неправильно подключаю? Вроде по документации сделал

2021-04-04 16:35 UTC, ant1quar requested changes
Привет. Ты неплохо справился. с dayjs - перебор. Использовать ее не нужно. Глянь мои комменты, если будут вопросы - пиши

2021-04-04 16:35 UTC, ant1quar commented on src/mock/mocks.js
> +import dayjs from 'dayjs';
Это задание нужно делать без внешних библиотек. Это моковые данные, которые не стоит перегружать лишней функциональностью. `dayjs` очень удобная библиотека, которая дает много методов преобразования формата даты и функций для работы с ней. Но использовать ее для генерации случайного числа с приставкой M или H - это как микроскопом гвозди забивать.
Нужно выпилить эту либу и переписать все функции, где она используется

2021-04-04 16:35 UTC, ant1quar commented on src/mock/mocks.js
> +  });
Это как-то сложненько. ты же обрезаешь кусок массива array с начала до случайной длины < `array.length` - это можно сделать проще - `return array.slice(0, generateRandomNumber(0, array.length))`
Но это не случайный массив элементов `array`. всегда будут только первые. так и задумано?

2021-04-04 16:35 UTC, ant1quar commented on src/mock/mocks.js
> +    isFavorite: Boolean(generateRandomNumber()),
Можно проще `!!generateRandomNumber()`

2021-04-04 16:35 UTC, ant1quar commented on src/mock/mocks.js
> +    //duration:,
Тебе не нужно использовать dayjs, я уже писал.
Тебе случайные данные нужно сгенерить без какой-то логики. - верни случайное число минут и добавь к нему `M` - это будут случайные данные.
А если хочется челлендж - можешь немного логики написать. Можно генерить две случайные даты в промежутке +- 6 часов от текущей. И вычислять сколько целых часов между ними и сколько целых минут.

2021-04-04 16:35 UTC, ant1quar commented on src/view/new-trip-point.js
> +  return list ;
Переделай на `map.join('')` или `reduce`. так будет короче и красивее

2021-04-04 16:35 UTC, ant1quar commented on src/view/new-trip-point.js
> +  return list ;
Актуально для всех таких функций

2021-04-04 16:35 UTC, ant1quar commented on src/view/new-trip-point.js
> +  }
Это лишняя проверка. 0 == false

2021-04-04 16:35 UTC, ant1quar commented on src/view/trip-info.js
> +    }).join(' — ');
Загадка. а зачем тут этот `filter`?

2021-04-04 16:35 UTC, ant1quar commented on src/utils.js
> +const minMax = require('dayjs/plugin/minMax');
Ну ты уже наверняка понял что нужно сделать с этой либой

2021-04-04 16:35 UTC, ant1quar commented on src/utils.js
> +};
ответ тот же

2021-04-05 08:03 UTC, IvanLysukhin commented on src/view/trip-info.js
> +    }).join(' — ');
Тут filter добавил, чтобы дубли убрать из массива 
К примеру, путешествие состоит из трех точек, две из которых в одном городе 
И чтобы строка была 'Москва - Санкт-Петербург', а не  'Москва - Санкт-Петербург - Санкт-Петербург'

2021-04-05 09:26 UTC, ant1quar commented on src/view/trip-info.js
> +    }).join(' — ');
А ты знаешь про Set?

2021-04-05 10:04 UTC, IvanLysukhin commented on src/view/trip-info.js
> +    }).join(' — ');
Вот это имеешь в виду? https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Set
Нет, не знаю( 
Не приходилось пользоваться на предыдущем курсе
Почему ей лучше использовать, чем filter?

2021-04-05 16:35 UTC, IvanLysukhin commented on src/view/trip-info.js
> +
Здесь пытаюсь сравнивать случайные даты, чтобы найти первое и последнее число путешествия
Но пока выходит не очень
Предполагаю, что с реальными данными будет проще)

2021-04-06 09:53 UTC, merged