Перевёл компоненты на классы
htmlacademy-ecmascript/1482089-big-trip-14 pull request #5
Opened 2021-04-10 13:47 UTC by IvanLysukhin

2021-04-10 13:51 UTC, IvanLysukhin commented on src/view/content-list.js
> +}
Делал по аналогии, как показывали на лайве, только где-то добавлял в конструктор возможность  добавить необходимых для отрисовки значений. По итогу вроде все везде работает на классах также, как и то этого.
Меня только смущает, что в каждом компоненте код класса почти один и тот же. Что с этим можно сделать? Сделать какой то один класс и потом туда передавать? Или об этом речь пойдет дальше на курсах?

2021-04-10 16:38 UTC, IvanLysukhin commented on src/utils.js
> +};
Не знаю как быть с этой функцией
Изначально как и все перевёл ее на класс, но когда начала работать над открытием/закрытием формы редактирования, увидел, что чекбоксов нет
Подумал что эта функция нужна только как вспомогательная для отрисовки  списка чекбоксов типов транспорта в формах редактировани и создания новой точки, и вынес её в utils 
Могу ли её здесь оставить? Или же она идет как компонент и требует отдельного файла?

2021-04-11 22:05 UTC, ant1quar commented on src/view/content-list.js
> +}
Хорошо, что ты заметил. Буквально на следующей лекции это будет рассмотрено. Мы создадим класс, который будет хранить этот функционал и будем наследоваться от него.

2021-04-11 22:19 UTC, ant1quar requested changes

2021-04-11 22:19 UTC, ant1quar commented on src/utils.js
> +const creatElementDOM = (template) => {
`creatE` - создать от английского. на притериях могут завернуть за такое. поправь, пожалуйста везде

2021-04-11 22:19 UTC, ant1quar commented on src/utils.js
> +    const lowerType = array[i].toLowerCase();
А зачем array[i], если у тебя элемент залетает в первый параметр?
```
const typesList = array.map((element) => {
    const lowerType = element.toLowerCase();
```

2021-04-11 22:19 UTC, ant1quar commented on src/utils.js
> +};
Пожалуй нет. надо посмотреть снова почему у тебя не генерятся чекбоксы.
Может ты не передаешь типы? или эта функция вообще не вызывается?
Это не вспомогательная функция - это вьюха, которая генерирует разметку. поэтому для нее нужно завести отдельный класс

2021-04-11 22:19 UTC, ant1quar commented on src/view/content-list.js
>            </ul>`;
Надо убрать лишние переносы строк

2021-04-11 22:19 UTC, ant1quar commented on src/view/filters.js
> +             <input id="filter-${array[i]}" class="trip-filters__filter-input  visually-hidden" type="radio" name="trip-filter" value="${array[i]}">
Тут снова `array[i]`

2021-04-13 07:41 UTC, merged