Module5 task1
htmlacademy-ecmascript/1482089-big-trip-14 pull request #8
Opened 2021-04-18 10:47 UTC by IvanLysukhin

2021-04-18 10:52 UTC, IvanLysukhin commented on src/presenter/point.js
> +    this._handlerEditForm = this._handlerEditForm.bind(this);
Правильно ли я понимаю, что здесь мы привязываем контекст данного объекта к методом, чтобы при подписки они работали? Но при этом мы уже привязали callback в view компоненте точки маршрута. Можешь пояснить попроще что и как здесь происходит? Зачем дважды привязывать контекст в presenter и view ?

2021-04-18 11:26 UTC, IvanLysukhin commented on src/presenter/menu.js
> +}
Законно ли перенести сейчас меню в отдельный презентер? И правильно я его описал?
Или пока стоит вернуть как было в main.js в точке входа?

2021-04-18 18:11 UTC, IvanLysukhin commented on src/presenter/trip.js
> +  }
Пытаюсь разобраться как все это работает...
Разобрать все связи методов между собой...но путаюсь только сильнее
Пока вроде все работает, но сейчас работа больше похожа на адаптацию коммитов из демо проекта на этот.
Как быть? Как разобраться в связях? Может есть какой-нибудь совет?

2021-04-19 06:47 UTC, IvanLysukhin commented on src/presenter/point.js
> +    this._changeMode = changeMode;
Здесь в конструкторе мы добавляем еще один параметр, который будет коллбэком в презентере маршрута.

2021-04-19 06:48 UTC, IvanLysukhin commented on src/presenter/point.js
> +    this._changeMode = changeMode;
Который будет сбрасывать форму до точки

2021-04-19 06:49 UTC, IvanLysukhin commented on src/presenter/point.js
> +    this._mode = pointMode.DEFAULT;
По - умолчанию у точек будет режим дефолт

2021-04-19 06:51 UTC, IvanLysukhin commented on src/presenter/point.js
> +
Этот метод проверяет режим точки, и сбрасывает ее до режима по умолчанию.

2021-04-19 06:52 UTC, IvanLysukhin commented on src/presenter/point.js
> +    this._mode = pointMode.EDITING;
Здесь выполняется коллбэк переданный в презентере маршрута и изменяется свойство презентера точки.

2021-04-19 06:53 UTC, IvanLysukhin commented on src/presenter/trip.js
>  }
Здесь получается круг замыкается между маршрутом и точкой. Этот тот самый коллбэк, который передаём в презентер точки, для сброса до режима по - умолчанию

2021-04-20 22:19 UTC, ant1quar requested changes

2021-04-20 22:19 UTC, ant1quar commented on src/presenter/trip.js
> +  }
Тут стоит придерживаться той же логики, как и в первом задлании - где ты разбивал мокапы на функции-компоненты.
Презентер у тебя должен формировать всю твою структуру приложения. Аместе с хедером, статистикой, сортировкой и тд. поэтому лучше его назвать абстрактнее. например Layer, Template, или лучше App - он жеж всю приложуху генерит)
Я тут скрин накидал https://pastenow.ru/f46fc747a98cbfdd028ec253a86aba12
Вот смотри, `Layer` там это твой презентер - красный цвет
1) У него есть метод `init`, в нем он дергает два своих метода `this._renderHeader` и `this._renderBoard`
2) `this._renderHeader` - зеленый цвет. Он должен отрендерить весь хедер (всю синюю полоску), значит должен дернуть еще два метода `this._renderMenu` и `this._renderSorting` чтобы меню и сортировку отрисовать соответственно.
3) `this._renderBoard` - коричневый цвет. он должен разрулить с маршрутом и отрисовать кучу `point`
Все связи я стрелками указал. Понятное дело, тут не все компоненты, а сама идея - чтобы у тебя класс был разбит на мелкие методы, которые изолированно делают что-то одно.

2021-04-20 22:19 UTC, ant1quar commented on src/view/trip-point.js
> -  return `<li class="trip-events__item">
А зачем тут ли исчез?

2021-04-20 22:19 UTC, ant1quar commented on src/presenter/point.js
> +  initialize (point) {
Тут не совсем верная логика. у тебя презентер должен быть жестко связан со ссылкой на объект данных, которые  он рендерит. Тебе point нужно в конструкторе передавать. Это ж презентер для отрисовки одной точки маршрута?

2021-04-21 08:55 UTC, IvanLysukhin commented on src/view/trip-point.js
> -  return `<li class="trip-events__item">
Я его в отдельный компонент вынес
У меня там проблемка возникла при смене точки на форму редактирования

2021-04-21 11:42 UTC, merged